[env:heltec-v4-custom-sensor-pozzo] 
extends = esp32s3_base
board = heltec_v4
board_check = true
board_build.partitions = default_16MB.csv
build_flags = 
  ${esp32s3_base.build_flags}
  -D HELTEC_V4
  -I variants/custom/heltec_v4_custom_sensor_pozzo
lib_deps =
    ${esp32s3_base.lib_deps}
    adafruit/Adafruit ADS1X15@^2.6.0
    jmparatte/jm_PCF8574@^2.0.0
	  jmparatte/jm_LCM2004A_I2C@^2.0.0
    kosme/arduinoFFT@^2.0.4
