[env:heltec-v4-custom-sensor-pozzo] 
extends = esp32s3_base
board = heltec_v4
board_check = true
board_build.partitions = default_16MB.csv
build_flags = 
  ${esp32s3_base.build_flags}
  -D HELTEC_V4
  -I variants/custom/heltec_v4_custom_sensor_pozzo
